add_newline = false
format = "$line_break$os$time$git_branch$git_status$fill $conda$python$vagrant$fill $aws$azure$gcloud$kubernetes$fill $cmd_duration$status $line_break$line_break$sudo$username$hostname$directory$character"

[aws]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $profile( [\\($region\\)]($style bg:black inverted italic))]($style bg:black inverted)[]($style) "
style = "yellow bold"
symbol = "󰸏"

[azure]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $profile]($style bg:black inverted)[]($style) "
style = "cyan bold"
symbol = ""

[character]
disabled = false
error_symbol = "[›](red bold)"
format = "$symbol "
success_symbol = "[›](white)"
vimcmd_replace_one_symbol = "[⑇](green bold)›"
vimcmd_replace_symbol = "[⑇](blue dimmed bold)›"
vimcmd_symbol = "[⑆](bright-yellow bold)›"
vimcmd_visual_symbol = "[⑆](purple bold)›"

[cmd_duration]
disabled = false
format = "[]($style)[[ ]($style inverted)$duration]($style inverted)[]($style) "
min_time = 1
style = "bright-yellow"

[conda]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $environment]($style bg:black inverted)[]($style) "
style = "bright-green"
symbol = "󱔎"

[directory]
disabled = false
fish_style_pwd_dir_length = 2
format = "[$path]($style)"
repo_root_style = "cyan bold"
style = "cyan dimmed bold"
truncation_length = 3

[fill]
disabled = false
symbol = "-"

[gcloud]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $account(@$domain)( [\\($region\\)]($style bg:black inverted italic))]($style bg:black inverted)[]($style) "
style = "bright-red"
symbol = ""

[git_branch]
disabled = false
format = "[]($style)[$symbol$branch ]($style bg:black inverted)"
style = "green"
symbol = " "
truncation_length = 16

[git_status]
disabled = false
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "="
deleted = "[-${count} ](fg:bright-red bg:bright-black)"
diverged = "↑${ahead_count} ⇣${behind_count}"
format = "[ ]($style inverted)$all_status[$ahead_behind]($style bg:bright-white inverted)[]($style) "
modified = "[!${count} ](fg:bright-yellow bg:bright-black)"
renamed = "[»${count} ](fg:bright-yellow bg:bright-black)"
staged = "[+${count} ](fg:bright-green bg:bright-black)"
stashed = "[*${count} ](fg:bright-blue bg:bright-black)"
style = "bright-black"
untracked = "[?${count} ](fg:bright-red bg:bright-black)"
up_to_date = "[](fg:bright-green bg:bright-black)"

[hostname]
disabled = false
format = "[$ssh_symbol$hostname]($style):"
ssh_only = false
style = "green dimmed bold"

[kubernetes]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $context(/$namespace)]($style bg:black inverted)[]($style) "
style = "bright-blue"
symbol = "󱃾"

[os]
disabled = false
format = "[](fg:$style)[$symbol]($style inverted)[]($style bg:bright-black)"
style = "blue"

  [os.symbols]
  Alpine = ""
  Amazon = ""
  Android = ""
  Arch = ""
  CentOS = ""
  Debian = ""
  DragonFly = ""
  Emscripten = ""
  EndeavourOS = ""
  Fedora = ""
  FreeBSD = ""
  Garuda = "󰛓"
  Gentoo = ""
  HardenedBSD = "󰞌"
  Illumos = "󰈸"
  Linux = ""
  Macos = ""
  Manjaro = ""
  Mariner = ""
  MidnightBSD = ""
  Mint = ""
  NetBSD = ""
  NixOS = ""
  OpenBSD = "󰈺"
  OracleLinux = "󰌷"
  Pop = ""
  Raspbian = ""
  RedHatEnterprise = ""
  Redhat = ""
  Redox = "󰀘"
  SUSE = ""
  Solus = "󰠳"
  Ubuntu = ""
  Unknown = ""
  Windows = ""
  openSUSE = ""

[python]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $version]($style bg:black inverted)[]($style) "
style = "green"
symbol = "󰌠"

[status]
disabled = false
format = "[$status $symbol]($style)"
map_symbol = true
not_executable_symbol = "󰮘"
not_found_symbol = "󰍉"
pipestatus = true
pipestatus_format = "[$pipestatus]($style)"
pipestatus_segment_format = "$status"
recognize_signal_code = true
sigint_symbol = "󰚌"
signal_symbol = ""
style = "bright-red"
success_symbol = ""
symbol = ""

[sudo]
disabled = false
format = "[!](red)"

[time]
disabled = false
format = "[ $time]($style bg:bright-white inverted)[]($style) "
style = "bright-black"
time_format = "%H:%M"

[username]
disabled = false
format = "[$user@]($style)"
style_root = "red bold"
style_user = "yellow bold"

[vagrant]
disabled = false
format = "[](black)[$symbol ](fg:bright-white bg:black)[ $profile]($style bg:black inverted)[]($style) "
style = "bright-purple"
symbol = ""
