# --- application version
packages:
    bitwarden_secret_manager:
        # renovate: datasource=github-tags depName=bitwarden/sdk-sm prefix=bws-
        version: bws-v1.0.0
        release_names:
            linux/amd64: bws-x86_64-unknown-linux-gnu-*.zip
            linux/arm64: bws-aarch64-unknown-linux-gnu-*.zip
            darwin/amd64: bws-x86_64-apple-darwin-*.zip
            darwin/arm64: bws-aarch64-apple-darwin-*.zip

    btop:
        # renovate: datasource=github-tags depName=aristocratos/btop
        version: latest
        release_names:
            linux/amd64: btop-x86_64-linux-musl.tbz
            linux/arm: btop-arm-linux-musleabi.tbz
            linux/arm64: btop-aarch64-linux-musl.tbz

    mise:
        # renovate: datasource=github-tags depName=jdx/mise
        version: latest
        release_names:
            linux/amd64: mise-*-linux-x64
            linux/arm: mise-*-linux-armv7
            linux/arm64: mise-*-linux-arm64
            darwin/amd64: mise-*-macos-x64
            darwin/arm64: mise-*-macos-arm64

    ocx:
        # renovate: datasource=github-tags depName=kdcokenny/ocx
        version: latest
        release_names:
            linux/amd64: ocx-linux-x64
            linux/arm64: ocx-linux-arm64
            darwin/amd64: ocx-darwin-x64
            darwin/arm64: ocx-darwin-arm64

    usage:
        # renovate: datasource=github-tags depName=jdx/usage
        version: latest
        release_names:
            linux/amd64: usage-x86_64-unknown-linux-gnu.tar.gz
            linux/arm64: usage-aarch64-unknown-linux-gnu.tar.gz
            darwin/amd64: usage-universal-apple-darwin.tar.gz
            darwin/arm64: usage-universal-apple-darwin.tar.gz
