# --- application version
packages:
  bitwarden_secret_manager:
    # renovate: datasource=github-tags depName=bitwarden/sdk-sm prefix=bws-
    version: bws-v1.0.0
    release_names:
      linux/amd64: bws-x86_64-unknown-linux-gnu-*.zip
      linux/arm64: bws-aarch64-unknown-linux-gnu-*.zip
      darwin/amd64: bws-x86_64-apple-darwin-*.zip
      darwin/arm64: bws-aarch64-apple-darwin-*.zip

  btop:
    # renovate: datasource=github-tags depName=aristocratos/btop
    version: latest
    release_names:
      linux/amd64: btop-x86_64-linux-musl.tbz 
      linux/arm: btop-arm-linux-musleabi.tbz 
      linux/arm64: btop-aarch64-linux-musl.tbz 

  direnv:
    # renovate: datasource=github-tags depName=direnv/direnv
    version: latest
    release_names:
      linux/amd64: direnv.linux-amd64
      linux/arm: direnv.linux-arm
      linux/arm64: direnv.linux-arm64
      darwin/amd64: direnv.darwin-amd64
      darwin/arm64: direnv.darwin-arm64

  lazygit:
    # renovate: datasource=github-tags depName=jesseduffield/lazygit
    version: latest
    release_names:
      linux/amd64: lazygit_*_Linux_x86_64.tar.gz
      linux/arm: lazygit_*_Linux_armv6.tar.gz
      linux/arm64: lazygit_*_Linux_arm64.tar.gz
      darwin/amd64: lazygit_*_Darwin_x86_64.tar.gz
      darwin/arm64: lazygit_*_Darwin_arm64.tar.gz

  mise:
    # renovate: datasource=github-tags depName=jdx/mise
    version: latest
    release_names:
      linux/amd64: mise-*-linux-x64
      linux/arm: mise-*-linux-armv7
      linux/arm64: mise-*-linux-arm64
      darwin/amd64: mise-*-macos-x64
      darwin/arm64: mise-*-macos-arm64

  usage:
    # renovate: datasource=github-tags depName=jdx/usage
    version: latest
    release_names:
      linux/amd64: usage-x86_64-unknown-linux-gnu.tar.gz 
      linux/arm64: usage-aarch64-unknown-linux-gnu.tar.gz 
      darwin/amd64: usage-universal-apple-darwin.tar.gz 
      darwin/arm64: usage-universal-apple-darwin.tar.gz 

  zoxide:
    # renovate: datasource=github-tags depName=ajeetdsouza/zoxide
    version: latest
    release_names:
      linux/amd64: zoxide-*-x86_64-unknown-linux-musl.tar.gz
      linux/arm: zoxide-*-armv7-unknown-linux-musleabihf.tar.gz
      linux/arm64: zoxide-*-aarch64-unknown-linux-musl.tar.gz
      darwin/amd64: zoxide-*-x86_64-apple-darwin.tar.gz
      darwin/arm64: zoxide-*-aarch64-apple-darwin.tar.gz
