# --- application version
packages:
  # renovate: datasource=github-tags depName=aristocratos/btop
  btop_version: v1.3.2

  # renovate: datasource=github-tags depName=direnv/direnv
  direnv_version: v2.34.0

  # renovate: datasource=github-tags depName=jdx/mise
  mise_version: v2024.7.3

  # renovate: datasource=github-tags depName=jdx/usage
  usage_version: v0.3.0
