# --- application version
packages:
  # renovate: datasource=github-tags depName=sharkdp/bat
  bat_version: v0.23.0

  # renovate: datasource=github-tags depName=direnv/direnv
  direnv_version: 2.32.3

  # renovate: datasource=github-tags depName=sharkdp/fd
  fd_version: v8.7.0

  # renovate: datasource=github-tags depName=junegunn/fzf
  fzf_version: 0.42.0
